name: Bedford Lab Research
description: Science updates on evolution, epidemiology and immunology from the Bedford lab at the Fred Hutch
baseurl: /blotter
url: http://laduplessis.github.io/

markdown: redcarpet
permalink: /:categories/:title/
future: true

redcarpet: 
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.nb"
  - "*.trees"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"
  
projects:
  - laduplessis/SkylineTutorial
  - trvrb/haplotypes
  - alvason/infectious-pulse
  - trvrb/phylodynamics-lecture
  - blab/baltic
